Update deploy-anchor.yml

diff --git a/.github/workflows/deploy-anchor.yml b/.github/workflows/deploy-anchor.yml
--- a/.github/workflows/deploy-anchor.yml
+++ b/.github/workflows/deploy-anchor.yml
@@ -51,6 +51,7 @@ jobs:
         anchor --version
 
     - name: Restore wallet keypair (signer)
+      working-directory: programs/arciumint-nft-gen
       run: |
         echo '${{ secrets.WALLET_KEY }}' > wallet.json
         solana config set --keypair wallet.json
@@ -66,7 +67,7 @@ jobs:
         solana address -k target/deploy/arciumintnftgen-keypair.json
 
     - name: Airdrop SOL to wallet
-      run: solana airdrop 0.2 -k wallet.json || echo "Airdrop failed, continuing anyway"
+      run: solana airdrop 0.2 -k programs/arciumint-nft-gen/wallet.json || echo "Airdrop failed, continuing anyway"
 
     - name: Confirm Program ID consistency
       working-directory: programs/arciumint-nft-gen
@@ -84,12 +85,18 @@ jobs:
         rm -rf programs/arciumint-nft-gen/.anchor
 
     - name: Build Anchor program
+      working-directory: programs/arciumint-nft-gen
       run: |
         ANCHOR_LOG=true anchor build --skip-lint
+
+    - name: Move .so to root target/deploy
+      run: |
+        mkdir -p target/deploy
+        cp programs/arciumint-nft-gen/target/deploy/arciumintnftgen.so target/deploy/arciumintnftgen.so
 
     - name: Deploy Anchor program to devnet
       working-directory: programs/arciumint-nft-gen
       run: |
         anchor deploy \
           --provider.cluster devnet \
-          --provider.wallet ../../wallet.json
+          --provider.wallet wallet.json
